### ISSUE TITLE
Model pose not match

### ISSUE THREAD

**Issue by zero-joke** [Det1999/ShapeMaker#3]
Hello, I use the checkpoints(full & partial) to test my data, I find the output model does not match very well with the target model.One diffierent point is that my point cloud data has more points(aroud 5000). Can you give me some suggestions to troubleshot this issue.

**Comment by zero-joke** [comment]
![image](https://github.com/Det1999/ShapeMaker/assets/65877841/72af526f-291b-4927-b40e-d24acfac4e9f)

**Comment by shangbuhuan13** [comment]
There are some reasons that may cause this problem. First, since the database is not big enough, it may not contain geometrically similar objects of the input. Second, the pose estimation doesn't work very well. In fact, we found that VNN in some cases even performs worse than PointNet++ in representation ability.  A solution may be changing the backbone to some latest transformer based architectures.

**Comment by ZhangCYG** [comment]
In fact, the number of the input point cloud is fixed in our model. I think you could sampling your original point cloud according with the same number of the released model, or you can train another model suitable for your number of points easily.

**Comment by zero-joke** [comment]
Thanks for your reply. Then I use the model of your dataset as input after undergoing RT transformation.  Retrieval is work well , but the pose still not aligned.I used checkpoints are:
            chair_log_full/TEXT_chair_full/model_199.pth
            chair_log_full/TEXT_NEWFULL_cage_retrieval/chair-12kpt/model_randd_199.pth
My test script is based on 'cage_EVAL.py' ，just changed test data loader. I don't know what went wrong.
![image](https://github.com/Det1999/ShapeMaker/assets/65877841/a46c6dd4-b651-4a77-82a1-73d1202e2ffa)

**Comment by Det1999** [comment]
During the testing phase, we vary the poses of shapes in the database randomly to use as targets. The network maps these targets to an invariant space, and shapes from the database are also mapped to the invariant space. In the invariant space, we conduct retrieval. 

Please check if the visualization of shapes is in the coordinates of the invariant space. It is important to note that even in the invariant space, there are still some differences in the poses of shapes. In our experiments, we have found a few examples of pose mismatches.

**Comment by ZhangCYG** [comment]
In fact, we only find few examples of small pose mismatches in our experiments, not at your extent. But it seems that your input target shape is partial according to your visualization. How's the result using partial model?
